/* eslint-disable jest/no-commented-out-tests */

// import { createElement } from 'lwc';
// import FirstLWCClass from 'c/firstLWCClass';

describe('c-first-lwc-class', () => {
    test('first testing' , () =>{
            expect(5).toBe(5);
    })

    // afterEach(() => {
    //     // The jsdom instance is shared across test cases in a single file so reset the DOM
    //     while (document.body.firstChild) {
    //         document.body.removeChild(document.body.firstChild);
    //     }
    // });


    // it('TODO: test case generated by CLI command, please fill in test logic', () => {
    //     // Arrange
    //     const element = createElement('c-first-lwc-class', {
    //         is: FirstLWCClass
    //     });
 
    //     // Act
    //     document.body.appendChild(element); 

    //     // Assert
    //     // const div = element.shadowRoot.querySelector('div');
    //     expect(1).toBe(1);
    // });
});













































